### ISSUE TITLE
Issue working by Ashley

### ISSUE THREAD

**Issue by aeapen** [aeapen/dragons#1]
Github issue working with collaborator

Ha Ha

**Comment by aeapen** [comment]
this was edited by you I know . Thx

**Comment by hfu569** [comment]
test

**Comment by aeapen** [comment]
ok. this was not fixed so it is somehow opened because of something else happening.  fixed it now.

**Comment by aeapen** [comment]
I am reopening it again.

**Comment by aeapen** [comment]
I closed it and reopened it.
